version: '3'
services:
  # mysql:
  #   image: mysql
  #   container_name: diesel.mysql
  #   volumes:
  #     - "mysql-data:/var/lib/mysql/:delegated"
  #     - "./docker/mysql/init:/docker-entrypoint-initdb.d"
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
  postgres:
    image: postgres
    container_name: diesel.postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "postgres-data1:/var/lib/postgresql/data:delegated"
      - "./docker/postgres/init:/docker-entrypoint-initdb.d"
    ports:
      - "5433:5432"
volumes:
  mysql-data:
    driver: local
  postgres-data1:
    driver: local
